### ISSUE TITLE
Add a requirements file

### ISSUE THREAD

**Issue by hypy13** [edrisranjbar/AparatDownloader#1]
سلام فایل requirments.txt 
میزاشتین عالی میشد

**Comment by edrisranjbar** [comment]
Hi,
I will put a requirements.txt file.
I didn't, because i had no virtual environment activated for this project at the time.

I responded in English on purpose, that everyone could read it and English is an international language.
but anyway.
Thanks for your contribution 🌹

**Comment by hypy13** [comment]
thanks

**Comment by edrisranjbar** [comment]
## TODO:
Here are steps to take in order to have a `requirements.txt` file which contains all packages we imported in the project with their explicit versions.
- [x] create a virtual environment for `python3` and name it as `.venv`
- [x] install packages within the actual `VENV`
- [x] get a `pip freeze` and save its result within `requirements.txt`
- [x] test the script and check all the necessary modules are imported and every thing works properly
- [x] update the `.readme` file and mention the venv steps for users
