### ISSUE TITLE
Separate core scrapping functionality from GUI

### ISSUE THREAD

**Issue by edrisranjbar** [edrisranjbar/AparatDownloader#6]
we need to **refactor** codes so that `GUI ` codes would be separated from the rest of the code. in our case we can create a new class called `Scrapper` and put all of the codes about `curling` and web scrapping inside that class. then we can import modules from that class as we want to.

## TODO:
Here are some of the steps we should take in order to make the codes cleaner.
- [x] have separate Core `class ` for scrapping called `Scrapper`
- [x] put scrapper in another file and import in `AparatDownloader.py`
- [x] rename methods
- [x] refactor `Scrapper` class
- [x] main file should only contains GUI stuff
