### ISSUE TITLE
write unit tests

### ISSUE THREAD

**Issue by edrisranjbar** [edrisranjbar/AparatDownloader#8]
we should write tests to make sure that the scrapper still works fine.
## TODO:
_Here are some steps to take_
- [x] test that all requirements are met
- [x] test that URL validation works
- [x] test we can get download link of a single video from URL
- [x] test that app returns proper error when URL does not exists
- [x] test that we can download and save the actual video file
- [x] test that we can get all video links from a playlist
- [x] test that the given URL is a playlist
- [x] test that we can get all resolutions available for a video
